# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: module-14
spec:
  selector:
    matchLabels:
      app: module-14
  replicas: 1
  template:
    metadata:
      labels:
        app: module-14
    spec:
      containers:
        - name: todo-app
          image: todo-app:prod
          imagePullPolicy: Never
          ports:
          - containerPort: 80
          env:
          
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
                secretKeyRef:
                  name: mongodb-connection-string
                  key: MONGODB_CONNECTION_STRING

          - name: SECRET_KEY
            valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
          
          - name: LOGGLY_TOKEN
            valueFrom:
                secretKeyRef:
                  name: loggly-token
                  key: LOGGLY_TOKEN

          - name: client_id
            valueFrom:
                secretKeyRef:
                  name: client-id
                  key: client_id

          - name: client_secret
            valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: client_secret

          - name: PORT
            value: "80"
          - name: "LOG_LEVEL"
            value: "DEBUG"
          - name: "OAUTHLIB_INSECURE_TRANSPORT"
            value: "1"